@host = http://localhost
@port = 5065
@Restaurants.API_HostAddress = https://localhost:7214


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=5
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json

{
  "id": 2,
  "name": "Test",
  "description": "test description",
  "hasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "Test2",
  "description": "test description2",
  "category": "Italian",
  "hasDelivery": true,
  "city": "London",
  "street": "test",
  "postalCode": "12-312",
  "dishes": []
}

###

@restaurantId=2
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "name" : "DishTest4",
  "description": "DishTest Description4",
  "price": 11.25,
  "kiloCalories" : 150
}

###

@dishId=6
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###
